# Generated by Django 2.2.2 on 2019-06-19 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
        migrations.AlterField(
            model_name='questions',
            name='date',
            field=models.DateField(default=datetime.date(2019, 6, 19)),
        ),
    ]
